FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copiar archivos de proyecto y restaurar dependencias
COPY TopFutbolAPI/*.csproj ./
RUN dotnet restore

# Copiar el resto del código y compilar
COPY TopFutbolAPI/. ./
RUN dotnet publish -c Release -o out

# Construir imagen final
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "TopFutbolAPI.dll"]