apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  connection-string: "Server=tcp:topfutbol.database.windows.net,1433;Initial Catalog=topFutbol;Persist Security Info=False;User ID=topfutbol;Password=D@t0s#2025!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"